name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # Déclenche l'action à chaque push sur main

permissions:
  contents: read
  pages: write
  id-token: write  # Nécessaire pour déployer sur GitHub Pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install sphinx_rtd_theme --break-system-packages

      - name: Build Sphinx documentation
        run: |
          sphinx-apidoc -o source/ ../src/
          sphinx-build -b html docs/source docs/build/html

      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html  # Dossier contenant la doc générée

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4